/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 22 19:41:57 GMT 2020
 */

package com.mytdev.resources4j;

import org.junit.Test;
import static org.junit.Assert.*;
import com.mytdev.resources4j.ResourcesException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ResourcesException_ESTest extends ResourcesException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ResourcesException resourcesException0 = new ResourcesException();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ResourcesException resourcesException0 = new ResourcesException("yY{&m.j]&'i[E;Y=");
      ResourcesException resourcesException1 = new ResourcesException(resourcesException0);
      assertFalse(resourcesException1.equals((Object)resourcesException0));
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ResourcesException resourcesException0 = new ResourcesException("yY{&m.j]&'i[E;Y=");
      ResourcesException resourcesException1 = new ResourcesException("", resourcesException0);
      assertFalse(resourcesException1.equals((Object)resourcesException0));
  }
}
