/*
 * This file was automatically generated by EvoSuite
 * Sun Apr 26 22:58:41 GMT 2020
 */

package com.sivalabs.jblogger.exceptions;

import org.junit.Test;
import static org.junit.Assert.*;
import com.sivalabs.jblogger.exceptions.JBloggerException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.lang.MockThrowable;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class JBloggerException_ESTest extends JBloggerException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable("6,y:b|#W+dPkKH26g)");
      JBloggerException jBloggerException0 = new JBloggerException(mockThrowable0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      JBloggerException jBloggerException0 = new JBloggerException("");
      JBloggerException jBloggerException1 = new JBloggerException("", jBloggerException0);
      assertFalse(jBloggerException1.equals((Object)jBloggerException0));
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      JBloggerException jBloggerException0 = new JBloggerException();
  }
}
